---
name: OpenVPN Client
version: dev
slug: openvpn
description: OpenVPN Client
url: https://github.com/haklai/haklai-hassio-addons/
ingress: true
ingress_stream: true
panel_icon: mdi:chart-areaspline
startup: application
hassio_api: true
arch:
  - aarch64
  - amd64
  - armv7
init: false
host_network: true
privileged:
  - NET_ADMIN
devices:
  - /dev/net/tun
map:
  - share:rw
